name: SEED 자동 배포 파이프라인

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: 자바 21 설정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application-prod.yml 파일 생성하기
        run: |
          echo "${{ secrets.APPLICATION_PROD_YML }}" | base64 --decode > ./src/main/resources/application-prod.yml

      - name: 그레이들 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 프로젝트 빌드
        run: ./gradlew clean build -x test

      - name: GHCR 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 도커 이미지 생성 및 푸시
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO/seed-server:latest .
          docker push ghcr.io/$REPO/seed-server:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: 라즈베리파이에서 GHCR 로그인
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 도커 컴포즈 실행
        run: |
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d
          docker image prune -f